[project]
name = "gemini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=1.64.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "strands-agents-tools>=0.2.21",
    "strands-agents[gemini]>=1.27.0",
]

[dependency-groups]
dev = [
    "hypothesis>=6.151.9",
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
pythonpath = ["."]
